"""add_hidden_flags_to_orders

Revision ID: 550659a2bf3d
Revises: 73408a22c33c
Create Date: 2026-03-08 12:52:23.646272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550659a2bf3d'
down_revision: Union[str, Sequence[str], None] = '73408a22c33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('hidden_for_user', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('orders', sa.Column('hidden_for_courier', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('topup_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('topup_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=True)
    op.drop_column('orders', 'hidden_for_courier')
    op.drop_column('orders', 'hidden_for_user')
    # ### end Alembic commands ###
